### ISSUE TITLE
"unknown argument" while compiling for web

### ISSUE THREAD

**Issue by Redlolz** [sm64pc/sm64pc#50]
I'm trying to build for web but I'm getting a bunch of errors while compiling, all related to `clang-10: error: unknown argument: '-fignore-exceptions'`
These are just two at the end of the output
```
clang-10: error: unknown argument: '-fignore-exceptions'
clang-10: error: unknown argument: '-fignore-exceptions'
emcc: error: '/sbin/clang -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=13 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/usr/lib/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/usr/lib/emsdk/upstream/emscripten/system/include -Xclang -isystem/usr/lib/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/usr/lib/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/usr/lib/emsdk/upstream/emscripten/system/local/include -Xclang -isystem/home/robin/.emscripten_cache/wasm/include -c -I/home/robin/.emscripten_cache/wasm/include/SDL2 -O2 -DUSING_GENERATED_CONFIG_H -w -DEMSCRIPTEN -fignore-exceptions /home/robin/.emscripten_ports/sdl2/SDL2-version_20/src/thread/generic/SDL_systhread.c -Xclang -isystem/usr/lib/emsdk/upstream/emscripten/system/include/SDL -c -o /home/robin/.emscripten_cache/wasm/ports-builds/sdl2/src/thread/generic/SDL_systhread.c.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
emcc: error: '/sbin/clang -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=13 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/usr/lib/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/usr/lib/emsdk/upstream/emscripten/system/include -Xclang -isystem/usr/lib/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/usr/lib/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/usr/lib/emsdk/upstream/emscripten/system/local/include -Xclang -isystem/home/robin/.emscripten_cache/wasm/include -c -I/home/robin/.emscripten_cache/wasm/include/SDL2 -O2 -DUSING_GENERATED_CONFIG_H -w -DEMSCRIPTEN -fignore-exceptions /home/robin/.emscripten_ports/sdl2/SDL2-version_20/src/thread/generic/SDL_systls.c -Xclang -isystem/usr/lib/emsdk/upstream/emscripten/system/include/SDL -c -o /home/robin/.emscripten_cache/wasm/ports-builds/sdl2/src/thread/generic/SDL_systls.c.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
```

I'm also getting a bunch of what looks like python error, possibly related to the issues above.
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/lib/emsdk/upstream/emscripten/tools/system_libs.py", line 89, in run_one_command
    shared.run_process(cmd, stdout=stdout, stderr=stderr, env=safe_env)
  File "/usr/lib/emsdk/upstream/emscripten/tools/shared.py", line 189, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/sbin/python3', '/usr/lib/emsdk/upstream/emscripten/emcc.py', '-c', '/home/robin/.emscripten_ports/sdl2/SDL2-version_20/src/SDL_dataqueue.c', '-o', '/home/robin/.emscripten_cache/wasm/ports-builds/sdl2/src/SDL_dataqueue.c.o', '-I/home/robin/.emscripten_cache/wasm/include/SDL2', '-O2', '-DUSING_GENERATED_CONFIG_H', '-w']' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/emsdk/upstream/emscripten/emcc.py", line 3982, in <module>
    sys.exit(run(sys.argv))
  File "/usr/lib/emsdk/upstream/emscripten/emcc.py", line 2118, in run
    cmd = get_clang_command(input_files)
  File "/usr/lib/emsdk/upstream/emscripten/emcc.py", line 2112, in get_clang_command
    args = system_libs.process_args(args, shared.Settings)
  File "/usr/lib/emsdk/upstream/emscripten/tools/system_libs.py", line 1958, in process_args
    args = port.process_args(Ports, args, settings, shared)
  File "/usr/lib/emsdk/upstream/emscripten/tools/ports/sdl2.py", line 98, in process_args
    get(ports, settings, shared)
  File "/usr/lib/emsdk/upstream/emscripten/tools/ports/sdl2.py", line 84, in get
    return [shared.Cache.get(libname, create, what='port')]
  File "/usr/lib/emsdk/upstream/emscripten/tools/cache.py", line 131, in get
    temp = creator()
  File "/usr/lib/emsdk/upstream/emscripten/tools/ports/sdl2.py", line 79, in create
    ports.run_commands(commands)
  File "/usr/lib/emsdk/upstream/emscripten/tools/system_libs.py", line 1753, in run_commands
    run_build_commands([add_args(c) for c in commands])
  File "/usr/lib/emsdk/upstream/emscripten/tools/system_libs.py", line 103, in run_build_commands
    pool.map_async(run_one_command, commands, chunksize=1).get(999999)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
subprocess.CalledProcessError: Command '['/sbin/python3', '/usr/lib/emsdk/upstream/emscripten/emcc.py', '-c', '/home/robin/.emscripten_ports/sdl2/SDL2-version_20/src/SDL_dataqueue.c', '-o', '/home/robin/.emscripten_cache/wasm/ports-builds/sdl2/src/SDL_dataqueue.c.o', '-I/home/robin/.emscripten_cache/wasm/include/SDL2', '-O2', '-DUSING_GENERATED_CONFIG_H', '-w']' returned non-zero exit status 1.
make: *** [Makefile:734: build/us_web/src/engine/behavior_script.o] Error 1
```

Edit: I'm on Arch Linux, have installed all the required packages including emsdk

**Comment by IvanDSM** [comment]
I searched through our codebase and could not find a reference to the -fignore-exceptions flag. This seems to be an issue with your installation of emsdk/emcc.

**Comment by attilaolah** [comment]
I think `-fignore-exception` was only released in clang-11, so it would not work with clang-10.

**Comment by attilaolah** [comment]
Specifically, when you use `emcc`, it will pass in arguments that are known to work with tip LLVM+Clang, but you're likely using your own LLVM. The solution is to download `emsdk`, use it to install LLVM (`emsdk install llvm-git-master-64bit`), and then set `LLVM_ROOT` in your `.emscripten` (or wherever is your `EM_CONFIG`) to the newly compiled LLVM path.

For reference, `-fignore-exceptions` was added in [D72644](https://reviews.llvm.org/D72644).
