### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by HinataNekoNya** [sm64pc/sm64pc#535]
On the last version i click on build and he make this:

make BETTERCAMERA=1 EXTERNAL_DATA=1 VERSION=eu -j4

make: cc: Aucun fichier ou dossier de ce type
make: *** [Makefile:54 : n64graphics] Erreur 127
Traceback (most recent call last):
  File "/home/deck/.SM64LinuxLauncher/SM64EX-Nightly/./extract_assets.py", line 286, in <module>
    main()
  File "/home/deck/.SM64LinuxLauncher/SM64EX-Nightly/./extract_assets.py", line 156, in main
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-s', '-C', 'tools/', 'n64graphics', 'skyconv', 'mio0', 'aifc_decode']' returned non-zero exit status 2.
Makefile:263: *** Failed to extract assets. Arrêt.

SteamOS (Based ArchLinux Distro)

**Comment by fgsfdsfgs** [comment]
You don't seem to have gcc installed.
On a related note, I didn't write that launcher so I can't help you with anything launcher specific.

**Comment by HinataNekoNya** [comment]
> You don't seem to have gcc installed. On a related note, I didn't write that launcher so I can't help you with anything launcher specific.

Yes but y launch command not in this launcher

**Comment by HinataNekoNya** [comment]
Repo is in but y use "make" in terminal
look first line.

**Comment by fgsfdsfgs** [comment]
Still, you need to ensure that you have gcc installed.

**Comment by HinataNekoNya** [comment]
i install gcc but now i have this:

make BETTERCAMERA=1 EXTERNAL_DATA=1 VERSION=eu -j4
Dans le fichier inclus depuis /usr/include/bits/posix1_lim.h:161,
                 depuis /usr/include/limits.h:195,
                 depuis /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include-fixed/limits.h:203,
                 depuis /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include-fixed/syslimits.h:7,
                 depuis /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include-fixed/limits.h:34,
                 depuis skyconv.c:8:
/usr/include/bits/local_lim.h:38:10: erreur fatale: linux/limits.h : Aucun fichier ou dossier de ce type
   38 | #include <linux/limits.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminée.
make: *** [Makefile:54 : skyconv] Erreur 1
Traceback (most recent call last):
  File "/home/deck/.SM64LinuxLauncher/SM64EX-Nightly/./extract_assets.py", line 286, in <module>
    main()
  File "/home/deck/.SM64LinuxLauncher/SM64EX-Nightly/./extract_assets.py", line 156, in main
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-s', '-C', 'tools/', 'n64graphics', 'skyconv', 'mio0', 'aifc_decode']' returned non-zero exit status 2.
Makefile:263: *** Failed to extract assets. Arrêt.

**Comment by HinataNekoNya** [comment]
sorry for french i copy and past of my terminal

**Comment by fgsfdsfgs** [comment]
Try installing the `base-devel` package, if that's available. Also try installing `linux-headers`.

**Comment by HinataNekoNya** [comment]
after installing;

make BETTERCAMERA=1 EXTERNAL_DATA=1 VERSION=eu -j4
```
Dans le fichier inclus depuis /usr/include/bits/posix1_lim.h:161,
                 depuis /usr/include/limits.h:195,
                 depuis /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include-fixed/limits.h:203,
                 depuis /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include-fixed/syslimits.h:7,
                 depuis /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include-fixed/limits.h:34,
                 depuis skyconv.c:8:
/usr/include/bits/local_lim.h:38:10: erreur fatale: linux/limits.h : Aucun fichier ou dossier de ce type
   38 | #include <linux/limits.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminée.

make: *** [Makefile:54 : skyconv] Erreur 1
Traceback (most recent call last):
  File "/home/deck/.SM64LinuxLauncher/SM64EX-Nightly/./extract_assets.py", line 286, in <module>
    main()
  File "/home/deck/.SM64LinuxLauncher/SM64EX-Nightly/./extract_assets.py", line 156, in main
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-s', '-C', 'tools/', 'n64graphics', 'skyconv', 'mio0', 'aifc_decode']' returned non-zero exit status 2.
Makefile:263: *** Failed to extract assets. Arrêt.
```

**Comment by fgsfdsfgs** [comment]
Did you install `linux-headers` as well?

**Comment by HinataNekoNya** [comment]
yes

**Comment by fgsfdsfgs** [comment]
Try installing `linux-api-headers` as well if that exists.

**Comment by HinataNekoNya** [comment]
```
src/pc/platform.c:93:10: fatal error: SDL2/SDL.h: No such file or directory
   93 | #include <SDL2/SDL.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:1016 : build/eu_pc/src/pc/platform.o] Erreur 1
make: *** Attente des tâches non terminées....
src/pc/pc_main.c: In function 'dispatch_audio_sptask':
src/pc/pc_main.c:64:43: warning: unused parameter 'spTask' [-Wunused-parameter]
   64 | void dispatch_audio_sptask(struct SPTask *spTask) {
      |                            ~~~~~~~~~~~~~~~^~~~~~
src/pc/pc_main.c: In function 'set_vblank_handler':
src/pc/pc_main.c:67:29: warning: unused parameter 'index' [-Wunused-parameter]
   67 | void set_vblank_handler(s32 index, struct VblankHandler *handler, OSMesgQueue *queue, OSMesg *msg) {
      |                         ~~~~^~~~~
src/pc/pc_main.c:67:58: warning: unused parameter 'handler' [-Wunused-parameter]
   67 | void set_vblank_handler(s32 index, struct VblankHandler *handler, OSMesgQueue *queue, OSMesg *msg) {
      |                                    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
src/pc/pc_main.c:67:80: warning: unused parameter 'queue' [-Wunused-parameter]
   67 | void set_vblank_handler(s32 index, struct VblankHandler *handler, OSMesgQueue *queue, OSMesg *msg) {
      |                                                                   ~~~~~~~~~~~~~^~~~~
src/pc/pc_main.c:67:95: warning: unused parameter 'msg' [-Wunused-parameter]
   67 | void set_vblank_handler(s32 index, struct VblankHandler *handler, OSMesgQueue *queue, OSMesg *msg) {
      |                                                                                       ~~~~~~~~^~~
cc -c -O2  -I include -I build/eu_pc -I build/eu_pc/include -I src -I . -DRAPI_GL=1 -DWAPI_SDL2=1 -DAAPI_SDL2=1 -DCAPI_SDL2=1 -DHAVE_SDL2=1 -I/usr/include/SDL2 -D_REENTRANT -DVERSION_EU -D_LANGUAGE_C -DNIGHTLY -DGIT_HASH="\"54cd27c\"" -DNON_MATCHING -DAVOID_UB -DF3DEX_GBI_2E -fno-strict-aliasing -fwrapv -DBETTERCAMERA -DEXT_OPTIONS_MENU -o build/eu_pc/src/pc/pc_main.o src/pc/pc_main.c
```

**Comment by fgsfdsfgs** [comment]
Did you [install the dependencies](https://github.com/sm64pc/sm64ex/wiki/Compiling-on-Linux)?

**Comment by HinataNekoNya** [comment]
yes bjt y have error with python Keyring

**Comment by HinataNekoNya** [comment]
on Arch y have keyring obligation

**Comment by fgsfdsfgs** [comment]
Unfortunately I can't help you with Arch.

**Comment by HinataNekoNya** [comment]
i try somthing

**Comment by HinataNekoNya** [comment]
it's gold if y erase python and y execute 

`sudo pacman -S base-devel sdl2 glew`

**Comment by HinataNekoNya** [comment]
dans archlinux sur une grande parti des distro python est deja installer

**Comment by HinataNekoNya** [comment]
```
/usr/include/SDL2/SDL_opengles2.h:35:10: fatal error: GLES2/gl2platform.h: No such file or directory
   35 | #include <GLES2/gl2platform.h>
```

 i have install SDL2

**Comment by HinataNekoNya** [comment]
y think y need install `mesa`

**Comment by HinataNekoNya** [comment]
same error after instalation

**Comment by fgsfdsfgs** [comment]
Did you install `glew`?

**Comment by HinataNekoNya** [comment]
> it's gold if y erase python and y execute
> 
> `sudo pacman -S base-devel sdl2 glew`

yes here

**Comment by fgsfdsfgs** [comment]
Can you post the full log?
Just from the error you posted, you seem to be building the game with `USE_GLES=1`. Not sure how or why. If you aren't doing that on purpose, try `make clean`.

**Comment by HinataNekoNya** [comment]
```
(2)(deck@SteamDeck-HinataNekoNya SM64EX-Nightly)$ make allclean
Failed to open baserom.us.z64! [Errno 2] No such file or directory: 'baserom.us.z64'
Makefile:263: *** Failed to extract assets. Arrêt.
(2)(deck@SteamDeck-HinataNekoNya SM64EX-Nightly)$ make allclean VERSION=eu
make : on entre dans le répertoire « /home/deck/.SM64LinuxLauncher/SM64EX-Nightly/tools »
make: rien à faire pour « default ».
make : on quitte le répertoire « /home/deck/.SM64LinuxLauncher/SM64EX-Nightly/tools »
make: *** Aucune règle pour fabriquer la cible « allclean ». Arrêt.

```

**Comment by fgsfdsfgs** [comment]
Try just `make clean` and then a fresh build. I forgot that this does not have the `allclean` target.

**Comment by HinataNekoNya** [comment]
how i can make log file ?

**Comment by fgsfdsfgs** [comment]
`make BETTERCAMERA=1 EXTERNAL_DATA=1 VERSION=eu -j4 > log.log`

**Comment by HinataNekoNya** [comment]
[log.log](https://github.com/sm64pc/sm64ex/files/12906265/log.log)

**Comment by fgsfdsfgs** [comment]
There's nothing in the log that would indicate why you're getting the GLES thing. By all accounts this shouldn't be happening.
Maybe try installing `libglvnd`?

**Comment by HinataNekoNya** [comment]
[log2.log](https://github.com/sm64pc/sm64ex/files/12906655/log.log)

**Comment by fgsfdsfgs** [comment]
Did you get any errors? I forgot that on Linux you'd need to do `> log.log 2>&1` instead of just `> log.log` for stderr to show up.
It looks like it got to at least the linking stage.

**Comment by HinataNekoNya** [comment]
i have erase old and get new x)

**Comment by HinataNekoNya** [comment]
more simply

**Comment by HinataNekoNya** [comment]
you see same error

**Comment by timmycodesforfun** [comment]
If you want help, please change your outputs to the English locale, so everyone can read the full logs, error messages and outputs of the installation process. It's not that hard to change.

If you need help for changing the locale temporarily consult the arch wiki or if you need more help ChatGPT for example.

(2)(deck@SteamDeck-HinataNekoNya SM64EX-Nightly)$ make allclean
Failed to open baserom.us.z64! [Errno 2] No such file or directory: 'baserom.us.z64'
Makefile:263: *** Failed to extract assets. Arrêt.
(2)(deck@SteamDeck-HinataNekoNya SM64EX-Nightly)$ make allclean VERSION=eu
make : on entre dans le répertoire « /home/deck/.SM64LinuxLauncher/SM64EX-Nightly/tools »
make: rien à faire pour « default ».
make : on quitte le répertoire « /home/deck/.SM64LinuxLauncher/SM64EX-Nightly/tools »
make: *** Aucune règle pour fabriquer la cible « allclean ». Arrêt.

^- I mean here, the script can't find the baserom.us.z64 for installation. Are you sure the baserom is in the right place?

And if you post the error log, you still need to post the relevant terminal output, when the makescript did exit and not just the log. This will make troubleshooting for others make way easier.

About dependencies, you wrote some incoherent and not understandable things:


"yes bjt y have error with python Keyring"

"on Arch y have keyring obligation"

"dans archlinux sur une grande parti des distro python est deja installer"  <- we don't understand french

"/usr/include/SDL2/SDL_opengles2.h:35:10: fatal error: GLES2/gl2platform.h: No such file or directory
   35 | #include <GLES2/gl2platform.h>

i have install SDL2"

Sorry, after this description, I doubt that all dependencies are correctly installed. 

So please post terminal outputs, where you show where your baserom is located and if all these dependencies are installed. If you have trouble installing these dependencies, please say so.

Also cloning git repo and compiling with make is a possibility, but it may be easier if you use the Arch User Repository (AUR) for sm64ex → sm64pc-git

Link: https://aur.archlinux.org/packages/sm64pc-git: for easier install, you can install an AUR-helper to install the repo. Then it's like pacman -S sm64pc-git (this won't work, because AUR packages are not official), but just another name like aurhelper -S sm64pc-git 

for example:


paru -S sm64pc-git 
pikaur -S sm64pc-git 
yay -S sm64pc-git 
(depending on which AUR helper you use / installed. I suggest paru or pikaur)

You can also use these PKGbuilds without an AUR helper. But I would recommend these helpers.

This will ensure that the dependencies are correctly installed. You will still have to put the baserom with the right region(US) and correct checksum in the right place/file location. But in my opinion, this is the easiest and a better way to install games/packages like these in Arch Linux. I don't have a SteamDeck, but as far as I know, the Arch User Repository (AUR) should work for the SteamDeck too. It's x64 architecture and I already found packages for the SteamDeck in the AUR (some packages about gyro control)

So maybe try that, good luck!

**Comment by TheBoxyBear** [comment]
Getting the same error installing on Arch through this repo and the AUR package. I installed all dependencies listed including mesa and linux neptune headers to resolve another issue. I tried the AUR helper route but having other issues there and I doubt it will be any different than installing from make or makepkg for AUR.

**Comment by xcom169** [comment]
EU version fails:

src/audio/port_eu.c: In function 'create_next_audio_buffer':
src/audio/port_eu.c:46:42: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   46 |         gAudioResetPresetIdToLoad = (u8) (s32) msg;
      |                                          ^
src/audio/port_eu.c:51:9: error: implicit declaration of function 'audio_reset_session' [-Wimplicit-function-declaration]
   51 |         audio_reset_session();
      |         ^~~~~~~~~~~~~~~~~~~
