### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by Spearmint3** [sm64pc/sm64pc#572]
I've tried to compile sm64ex, sm64ex-alo, and cream64_PC. they all give me this error:
$ make
make[1]: cc: No such file or directory
make[1]: *** [Makefile:54: n64graphics] Error 127
Traceback (most recent call last):
  File "/home/[user]/sm64ex/./extract_assets.py", line 285, in <module>
    main() if __name__ == "__main__" else None
    ^^^^^^
  File "/home/[user]/sm64ex/./extract_assets.py", line 156, in main
    subprocess.check_call(
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-s', '-C', 'tools/', 'n64graphics', 'skyconv', 'mio0', 'aifc_decode']' returned non-zero exit status 2.
Makefile:263: *** Failed to extract assets.  Stop.

what am I doing wrong?

**Comment by fgsfdsfgs** [comment]
You don't have gcc installed.
